# additives_db.py
# Comprehensive food additives dictionary (E numbers / INS numbers)
# safety: "green" = generally safe, "yellow" = use with caution, "red" = avoid

ADDITIVES_DB = {

    # ── COLOURS (E100–E199) ───────────────────────────────────────────────────
    "100": {"name": "Curcumin (Turmeric)", "safety": "green", "note": "Natural colour from turmeric, generally safe."},
    "101": {"name": "Riboflavin (Vitamin B2)", "safety": "green", "note": "Natural colour and essential nutrient."},
    "101a": {"name": "Riboflavin-5-Phosphate", "safety": "green", "note": "Form of Vitamin B2, generally safe."},
    "102": {"name": "Tartrazine", "safety": "yellow", "note": "May cause hyperactivity in children; banned in Norway."},
    "104": {"name": "Quinoline Yellow", "safety": "yellow", "note": "Linked to hyperactivity; banned in USA and Australia."},
    "107": {"name": "Yellow 2G", "safety": "yellow", "note": "Banned in several countries; limited use."},
    "110": {"name": "Sunset Yellow FCF", "safety": "yellow", "note": "May cause hyperactivity; requires warning label in EU."},
    "120": {"name": "Cochineal / Carmine", "safety": "yellow", "note": "Derived from insects; may cause allergic reactions."},
    "122": {"name": "Azorubine / Carmoisine", "safety": "yellow", "note": "Linked to hyperactivity in children."},
    "123": {"name": "Amaranth", "safety": "red", "note": "Banned in USA; ongoing safety concerns."},
    "124": {"name": "Ponceau 4R", "safety": "yellow", "note": "Requires hyperactivity warning label in EU."},
    "127": {"name": "Erythrosine", "safety": "yellow", "note": "High iodine content; restricted in some countries."},
    "128": {"name": "Red 2G", "safety": "red", "note": "Banned in EU and many countries; possible carcinogen."},
    "129": {"name": "Allura Red AC", "safety": "yellow", "note": "Linked to hyperactivity; requires EU warning label."},
    "131": {"name": "Patent Blue V", "safety": "yellow", "note": "May cause allergic reactions and anaphylaxis."},
    "132": {"name": "Indigotine / Indigo Carmine", "safety": "yellow", "note": "May cause nausea in large amounts."},
    "133": {"name": "Brilliant Blue FCF", "safety": "yellow", "note": "Banned in several European countries."},
    "140": {"name": "Chlorophylls", "safety": "green", "note": "Natural green colour from plants, safe."},
    "141": {"name": "Copper Chlorophylls", "safety": "green", "note": "Natural derivative, generally safe."},
    "142": {"name": "Green S", "safety": "yellow", "note": "Banned in several countries; limited data."},
    "150a": {"name": "Caramel Colour (Plain)", "safety": "green", "note": "Generally safe in normal amounts."},
    "150b": {"name": "Caramel Colour (Caustic Sulfite)", "safety": "yellow", "note": "May contain sulfite traces; under review."},
    "150c": {"name": "Caramel Colour (Ammonia)", "safety": "yellow", "note": "May contain trace contaminants; under review."},
    "150d": {"name": "Caramel Colour (Sulfite-Ammonia)", "safety": "yellow", "note": "Contains 4-MEI; potential carcinogen under study."},
    "151": {"name": "Brilliant Black BN", "safety": "yellow", "note": "Banned in USA and several other countries."},
    "153": {"name": "Carbon Black / Vegetable Carbon", "safety": "yellow", "note": "Banned in USA; approved in EU with limits."},
    "155": {"name": "Brown HT", "safety": "yellow", "note": "Banned in several countries including USA and Canada."},
    "160a": {"name": "Beta-Carotene", "safety": "green", "note": "Natural colour; precursor to Vitamin A."},
    "160b": {"name": "Annatto (Bixin, Norbixin)", "safety": "yellow", "note": "May cause allergic reactions in sensitive individuals."},
    "160c": {"name": "Paprika Extract (Capsanthin)", "safety": "green", "note": "Natural colour from paprika, generally safe."},
    "160d": {"name": "Lycopene", "safety": "green", "note": "Natural antioxidant from tomatoes, safe."},
    "161b": {"name": "Lutein", "safety": "green", "note": "Natural carotenoid; may support eye health."},
    "161g": {"name": "Canthaxanthin", "safety": "yellow", "note": "High doses may deposit in eyes; use restricted."},
    "162": {"name": "Beetroot Red / Betanin", "safety": "green", "note": "Natural colour from beetroot, safe."},
    "163": {"name": "Anthocyanins", "safety": "green", "note": "Natural plant pigments, generally safe."},
    "170": {"name": "Calcium Carbonates", "safety": "green", "note": "Generally safe; also a calcium supplement."},
    "171": {"name": "Titanium Dioxide", "safety": "red", "note": "Banned as food additive in EU (2022); possible carcinogen."},
    "172": {"name": "Iron Oxides and Hydroxides", "safety": "green", "note": "Used in decoration; safe at permitted levels."},
    "173": {"name": "Aluminium", "safety": "yellow", "note": "Decorative use only; excessive intake linked to neurotoxicity."},
    "174": {"name": "Silver", "safety": "yellow", "note": "Decorative use only; limited use permitted."},
    "175": {"name": "Gold", "safety": "green", "note": "Decorative use; inert and generally safe."},

    # ── PRESERVATIVES (E200–E299) ─────────────────────────────────────────────
    "200": {"name": "Sorbic Acid", "safety": "green", "note": "Generally safe; widely used preservative."},
    "201": {"name": "Sodium Sorbate", "safety": "green", "note": "Generally safe preservative."},
    "202": {"name": "Potassium Sorbate", "safety": "green", "note": "Generally safe; may cause mild skin irritation."},
    "203": {"name": "Calcium Sorbate", "safety": "green", "note": "Generally safe preservative."},
    "210": {"name": "Benzoic Acid", "safety": "yellow", "note": "Can form benzene with Vitamin C; avoid combining."},
    "211": {"name": "Sodium Benzoate", "safety": "yellow", "note": "May cause hyperactivity; avoid with ascorbic acid."},
    "212": {"name": "Potassium Benzoate", "safety": "yellow", "note": "Similar concerns as sodium benzoate."},
    "213": {"name": "Calcium Benzoate", "safety": "yellow", "note": "Similar concerns as sodium benzoate."},
    "214": {"name": "Ethylparaben", "safety": "yellow", "note": "Paraben preservative; endocrine disruption concerns."},
    "216": {"name": "Propylparaben", "safety": "yellow", "note": "Paraben; banned in food in EU for children's products."},
    "218": {"name": "Methylparaben", "safety": "yellow", "note": "Paraben; endocrine disruption concerns."},
    "220": {"name": "Sulphur Dioxide", "safety": "yellow", "note": "Can trigger asthma; must be labelled as allergen."},
    "221": {"name": "Sodium Sulphite", "safety": "yellow", "note": "May cause asthma reactions in sensitive individuals."},
    "222": {"name": "Sodium Hydrogen Sulphite", "safety": "yellow", "note": "Sulphite; allergen risk for asthmatics."},
    "223": {"name": "Sodium Metabisulphite", "safety": "yellow", "note": "Sulphite; allergen for asthmatics."},
    "224": {"name": "Potassium Metabisulphite", "safety": "yellow", "note": "Sulphite; allergen for asthmatics."},
    "225": {"name": "Potassium Sulphite", "safety": "yellow", "note": "Sulphite preservative; allergen risk."},
    "234": {"name": "Nisin", "safety": "green", "note": "Natural antimicrobial from bacteria, generally safe."},
    "235": {"name": "Natamycin (Pimaricin)", "safety": "green", "note": "Natural antifungal; used on cheese rinds."},
    "242": {"name": "Dimethyl Dicarbonate (DMDC)", "safety": "green", "note": "Breaks down rapidly after use; generally safe."},
    "249": {"name": "Potassium Nitrite", "safety": "red", "note": "Can form carcinogenic nitrosamines; use minimised."},
    "250": {"name": "Sodium Nitrite", "safety": "red", "note": "Linked to cancer risk; used in processed meats."},
    "251": {"name": "Sodium Nitrate", "safety": "yellow", "note": "Converts to nitrite in body; moderation advised."},
    "252": {"name": "Potassium Nitrate", "safety": "yellow", "note": "Converts to nitrite; use in small amounts only."},
    "260": {"name": "Acetic Acid (Vinegar)", "safety": "green", "note": "Natural preservative and flavouring, safe."},
    "261": {"name": "Potassium Acetate", "safety": "green", "note": "Generally safe acidity regulator."},
    "262": {"name": "Sodium Acetates", "safety": "green", "note": "Generally safe preservative and flavouring."},
    "263": {"name": "Calcium Acetate", "safety": "green", "note": "Generally safe; also a calcium supplement."},
    "270": {"name": "Lactic Acid", "safety": "green", "note": "Naturally produced in fermentation, safe."},
    "280": {"name": "Propionic Acid", "safety": "green", "note": "Generally safe; naturally found in Swiss cheese."},
    "281": {"name": "Sodium Propionate", "safety": "green", "note": "Generally safe bread preservative."},
    "282": {"name": "Calcium Propionate", "safety": "green", "note": "Generally safe; widely used in baked goods."},
    "283": {"name": "Potassium Propionate", "safety": "green", "note": "Generally safe preservative."},
    "290": {"name": "Carbon Dioxide", "safety": "green", "note": "Natural gas used for carbonation, safe."},
    "296": {"name": "Malic Acid", "safety": "green", "note": "Naturally found in apples; generally safe."},
    "297": {"name": "Fumaric Acid", "safety": "green", "note": "Naturally occurring acid, generally safe."},

    # ── ANTIOXIDANTS & ACIDITY REGULATORS (E300–E399) ────────────────────────
    "300": {"name": "Ascorbic Acid (Vitamin C)", "safety": "green", "note": "Essential vitamin and antioxidant, safe."},
    "301": {"name": "Sodium Ascorbate", "safety": "green", "note": "Vitamin C salt, generally safe."},
    "302": {"name": "Calcium Ascorbate", "safety": "green", "note": "Vitamin C calcium salt, generally safe."},
    "304": {"name": "Ascorbyl Palmitate", "safety": "green", "note": "Fat-soluble Vitamin C derivative, generally safe."},
    "306": {"name": "Tocopherols (Vitamin E)", "safety": "green", "note": "Natural antioxidant from vegetable oils, safe."},
    "307": {"name": "Alpha-Tocopherol (Vitamin E)", "safety": "green", "note": "Natural Vitamin E, safe."},
    "308": {"name": "Gamma-Tocopherol", "safety": "green", "note": "Form of Vitamin E, generally safe."},
    "309": {"name": "Delta-Tocopherol", "safety": "green", "note": "Form of Vitamin E, generally safe."},
    "310": {"name": "Propyl Gallate", "safety": "yellow", "note": "May cause allergic reactions; ongoing safety review."},
    "311": {"name": "Octyl Gallate", "safety": "yellow", "note": "May cause allergic reactions; restricted in some countries."},
    "312": {"name": "Dodecyl Gallate", "safety": "yellow", "note": "May cause allergic reactions."},
    "315": {"name": "Erythorbic Acid", "safety": "green", "note": "Antioxidant preservative, generally safe."},
    "316": {"name": "Sodium Erythorbate", "safety": "green", "note": "Generally safe antioxidant preservative."},
    "319": {"name": "TBHQ", "safety": "yellow", "note": "High doses linked to tumours in animal studies."},
    "320": {"name": "BHA (Butylated Hydroxyanisole)", "safety": "yellow", "note": "Possible carcinogen; banned in Japan."},
    "321": {"name": "BHT (Butylated Hydroxytoluene)", "safety": "yellow", "note": "Ongoing research; some countries restrict use."},
    "322": {"name": "Lecithin", "safety": "green", "note": "Natural emulsifier from soy or eggs; generally safe."},
    "325": {"name": "Sodium Lactate", "safety": "green", "note": "Salt of lactic acid, generally safe."},
    "326": {"name": "Potassium Lactate", "safety": "green", "note": "Salt of lactic acid, generally safe."},
    "327": {"name": "Calcium Lactate", "safety": "green", "note": "Calcium supplement and preservative, safe."},
    "330": {"name": "Citric Acid", "safety": "green", "note": "Naturally found in citrus fruits, generally safe."},
    "331": {"name": "Sodium Citrates", "safety": "green", "note": "Generally safe acidity regulator."},
    "332": {"name": "Potassium Citrates", "safety": "green", "note": "Generally safe acidity regulator."},
    "333": {"name": "Calcium Citrates", "safety": "green", "note": "Generally safe; also a calcium supplement."},
    "334": {"name": "Tartaric Acid", "safety": "green", "note": "Naturally found in grapes, generally safe."},
    "335": {"name": "Sodium Tartrates", "safety": "green", "note": "Generally safe acidity regulator."},
    "336": {"name": "Potassium Tartrates", "safety": "green", "note": "Generally safe acidity regulator."},
    "337": {"name": "Sodium Potassium Tartrate", "safety": "green", "note": "Generally safe acidity regulator."},
    "338": {"name": "Phosphoric Acid", "safety": "yellow", "note": "High intake linked to reduced bone density."},
    "339": {"name": "Sodium Phosphates", "safety": "yellow", "note": "High intake may affect kidney function."},
    "340": {"name": "Potassium Phosphates", "safety": "yellow", "note": "Moderation advised; high intake affects kidneys."},
    "341": {"name": "Calcium Phosphates", "safety": "green", "note": "Generally safe; used as raising agent."},
    "342": {"name": "Ammonium Phosphates", "safety": "green", "note": "Generally safe raising agent."},
    "343": {"name": "Magnesium Phosphates", "safety": "green", "note": "Generally safe; also a magnesium supplement."},
    "350": {"name": "Sodium Malates", "safety": "green", "note": "Generally safe acidity regulator."},
    "351": {"name": "Potassium Malates", "safety": "green", "note": "Generally safe acidity regulator."},
    "352": {"name": "Calcium Malates", "safety": "green", "note": "Generally safe acidity regulator."},
    "355": {"name": "Adipic Acid", "safety": "green", "note": "Naturally in beetroot; generally safe."},
    "363": {"name": "Succinic Acid", "safety": "green", "note": "Naturally occurring acid; generally safe."},
    "375": {"name": "Niacin (Vitamin B3)", "safety": "green", "note": "Essential vitamin; safe in food amounts."},
    "385": {"name": "Calcium Disodium EDTA", "safety": "yellow", "note": "May deplete minerals with high intake; moderation advised."},

    # ── THICKENERS / STABILISERS / EMULSIFIERS (E400–E499) ───────────────────
    "400": {"name": "Alginic Acid", "safety": "green", "note": "Natural seaweed extract; generally safe."},
    "401": {"name": "Sodium Alginate", "safety": "green", "note": "Natural seaweed extract; generally safe."},
    "402": {"name": "Potassium Alginate", "safety": "green", "note": "Natural seaweed extract; generally safe."},
    "404": {"name": "Calcium Alginate", "safety": "green", "note": "Natural seaweed extract; generally safe."},
    "405": {"name": "Propylene Glycol Alginate", "safety": "yellow", "note": "Generally safe; some concerns at high intake."},
    "406": {"name": "Agar", "safety": "green", "note": "Natural seaweed gel; generally safe."},
    "407": {"name": "Carrageenan", "safety": "yellow", "note": "May cause inflammation in large amounts; under review."},
    "407a": {"name": "Processed Eucheuma Seaweed", "safety": "yellow", "note": "Similar concerns as carrageenan."},
    "410": {"name": "Locust Bean Gum (Carob Gum)", "safety": "green", "note": "Natural thickener from carob beans; safe."},
    "412": {"name": "Guar Gum", "safety": "green", "note": "Natural thickener from guar beans; safe."},
    "413": {"name": "Tragacanth", "safety": "green", "note": "Natural plant gum; generally safe."},
    "414": {"name": "Acacia Gum (Gum Arabic)", "safety": "green", "note": "Natural plant gum; generally safe."},
    "415": {"name": "Xanthan Gum", "safety": "green", "note": "Fermentation product; generally safe."},
    "416": {"name": "Karaya Gum", "safety": "yellow", "note": "May cause allergic reactions in sensitive individuals."},
    "417": {"name": "Tara Gum", "safety": "green", "note": "Natural plant gum; generally safe."},
    "418": {"name": "Gellan Gum", "safety": "green", "note": "Fermentation product; generally safe."},
    "420": {"name": "Sorbitol", "safety": "yellow", "note": "Laxative effect in large amounts (>50g/day)."},
    "421": {"name": "Mannitol", "safety": "yellow", "note": "May cause digestive discomfort in large amounts."},
    "422": {"name": "Glycerol (Glycerin)", "safety": "green", "note": "Naturally occurring; generally safe."},
    "425": {"name": "Konjac (Glucomannan)", "safety": "yellow", "note": "Can cause choking if not properly hydrated; take with water."},
    "430": {"name": "Polyoxyethylene Stearate", "safety": "yellow", "note": "May affect gut permeability; limited data."},
    "432": {"name": "Polysorbate 20", "safety": "yellow", "note": "May affect gut bacteria; ongoing research."},
    "433": {"name": "Polysorbate 80", "safety": "yellow", "note": "May affect gut microbiome and inflammation."},
    "434": {"name": "Polysorbate 40", "safety": "yellow", "note": "Similar concerns as polysorbate 80."},
    "435": {"name": "Polysorbate 60", "safety": "yellow", "note": "Similar concerns as polysorbate 80."},
    "436": {"name": "Polysorbate 65", "safety": "yellow", "note": "Similar concerns as polysorbate 80."},
    "440": {"name": "Pectin", "safety": "green", "note": "Natural fibre from fruit; safe."},
    "442": {"name": "Ammonium Phosphatides", "safety": "green", "note": "Emulsifier used in chocolate; generally safe."},
    "450": {"name": "Diphosphates", "safety": "yellow", "note": "High phosphate intake linked to kidney issues."},
    "451": {"name": "Triphosphates", "safety": "yellow", "note": "Phosphate load; moderation advised."},
    "452": {"name": "Polyphosphates", "safety": "yellow", "note": "May affect kidney function in high amounts."},
    "460": {"name": "Microcrystalline Cellulose (MCC)", "safety": "green", "note": "Inert plant fibre; generally safe."},
    "461": {"name": "Methyl Cellulose", "safety": "green", "note": "Modified cellulose; generally safe."},
    "462": {"name": "Ethyl Cellulose", "safety": "green", "note": "Modified cellulose; generally safe."},
    "463": {"name": "Hydroxypropyl Cellulose", "safety": "green", "note": "Modified cellulose; generally safe."},
    "464": {"name": "Hydroxypropyl Methyl Cellulose (HPMC)", "safety": "green", "note": "Modified cellulose; generally safe."},
    "465": {"name": "Methyl Ethyl Cellulose", "safety": "green", "note": "Modified cellulose; generally safe."},
    "466": {"name": "Sodium Carboxymethyl Cellulose (CMC)", "safety": "green", "note": "Generally safe thickener."},
    "470": {"name": "Salts of Fatty Acids", "safety": "green", "note": "Generally safe emulsifiers and stabilisers."},
    "471": {"name": "Mono- and Diglycerides of Fatty Acids", "safety": "green", "note": "Widely used emulsifier; generally safe."},
    "472a": {"name": "Acetic Acid Esters of Mono- and Diglycerides", "safety": "green", "note": "Emulsifier; generally safe."},
    "472b": {"name": "Lactic Acid Esters of Mono- and Diglycerides", "safety": "green", "note": "Emulsifier; generally safe."},
    "472c": {"name": "Citric Acid Esters of Mono- and Diglycerides", "safety": "green", "note": "Emulsifier; generally safe."},
    "472d": {"name": "Tartaric Acid Esters of Mono- and Diglycerides", "safety": "green", "note": "Emulsifier; generally safe."},
    "472e": {"name": "DATEM", "safety": "yellow", "note": "Generally safe; high intake may affect heart."},
    "473": {"name": "Sucrose Esters of Fatty Acids", "safety": "green", "note": "Generally safe emulsifier."},
    "475": {"name": "Polyglycerol Esters of Fatty Acids", "safety": "green", "note": "Generally safe emulsifier."},
    "476": {"name": "Polyglycerol Polyricinoleate (PGPR)", "safety": "green", "note": "Used in chocolate; generally safe."},
    "477": {"name": "Propylene Glycol Esters of Fatty Acids", "safety": "yellow", "note": "Generally safe; propylene glycol concerns at high dose."},
    "481": {"name": "Sodium Stearoyl Lactylate (SSL)", "safety": "green", "note": "Generally safe emulsifier."},
    "482": {"name": "Calcium Stearoyl Lactylate (CSL)", "safety": "green", "note": "Generally safe emulsifier."},
    "491": {"name": "Sorbitan Monostearate", "safety": "green", "note": "Generally safe emulsifier."},
    "492": {"name": "Sorbitan Tristearate", "safety": "green", "note": "Generally safe emulsifier."},
    "493": {"name": "Sorbitan Monolaurate", "safety": "green", "note": "Generally safe emulsifier."},
    "494": {"name": "Sorbitan Monooleate", "safety": "green", "note": "Generally safe emulsifier."},
    "495": {"name": "Sorbitan Monopalmitate", "safety": "green", "note": "Generally safe emulsifier."},

    # ── FLAVOUR ENHANCERS (E620–E650) ─────────────────────────────────────────
    "620": {"name": "Glutamic Acid", "safety": "yellow", "note": "May cause reactions in MSG-sensitive individuals."},
    "621": {"name": "Monosodium Glutamate (MSG)", "safety": "yellow", "note": "May cause reactions in sensitive people."},
    "622": {"name": "Monopotassium Glutamate", "safety": "yellow", "note": "Similar concerns as MSG."},
    "623": {"name": "Calcium Diglutamate", "safety": "yellow", "note": "Similar concerns as MSG."},
    "624": {"name": "Monoammonium Glutamate", "safety": "yellow", "note": "Similar concerns as MSG."},
    "625": {"name": "Magnesium Diglutamate", "safety": "yellow", "note": "Similar concerns as MSG."},
    "627": {"name": "Disodium Guanylate", "safety": "yellow", "note": "Often combined with MSG; avoid if gout-prone."},
    "631": {"name": "Disodium Inosinate", "safety": "yellow", "note": "Often combined with MSG; avoid if gout-prone."},
    "635": {"name": "Disodium 5-Ribonucleotides", "safety": "yellow", "note": "Combination of 627 and 631; same concerns."},
    "636": {"name": "Maltol", "safety": "green", "note": "Naturally in roasted malt; generally safe."},
    "637": {"name": "Ethyl Maltol", "safety": "green", "note": "Synthetic flavour enhancer; generally safe."},
    "640": {"name": "Glycine", "safety": "green", "note": "Amino acid; generally safe."},

    # ── SWEETENERS (E950–E969) ────────────────────────────────────────────────
    "950": {"name": "Acesulfame K", "safety": "yellow", "note": "Some studies suggest effects on gut bacteria."},
    "951": {"name": "Aspartame", "safety": "yellow", "note": "Classified as possibly carcinogenic by IARC (2023); avoid if PKU."},
    "952": {"name": "Cyclamate", "safety": "yellow", "note": "Banned in USA; approved in EU with limits."},
    "953": {"name": "Isomalt", "safety": "yellow", "note": "Sugar alcohol; laxative effect in large amounts."},
    "954": {"name": "Saccharin", "safety": "yellow", "note": "Oldest artificial sweetener; some cancer concerns in animal studies."},
    "955": {"name": "Sucralose", "safety": "yellow", "note": "May affect gut bacteria and insulin response."},
    "957": {"name": "Thaumatin", "safety": "green", "note": "Natural protein sweetener from katemfe fruit; safe."},
    "960": {"name": "Steviol Glycosides (Stevia)", "safety": "green", "note": "Natural sweetener from stevia plant; generally safe."},
    "961": {"name": "Neotame", "safety": "green", "note": "Generally safe; approved by major food authorities."},
    "962": {"name": "Aspartame-Acesulfame Salt", "safety": "yellow", "note": "Combination sweetener; same concerns as aspartame."},
    "965": {"name": "Maltitol", "safety": "yellow", "note": "Sugar alcohol; laxative effect in large amounts."},
    "966": {"name": "Lactitol", "safety": "yellow", "note": "Sugar alcohol; laxative effect in large amounts."},
    "967": {"name": "Xylitol", "safety": "yellow", "note": "Safe for humans; highly toxic to dogs."},
    "968": {"name": "Erythritol", "safety": "green", "note": "Sugar alcohol; better tolerated than others; generally safe."},
    "969": {"name": "Advantame", "safety": "green", "note": "High-intensity sweetener; approved by FDA and EFSA."},

    # ── MISCELLANEOUS (E500–E599) ─────────────────────────────────────────────
    "500": {"name": "Sodium Carbonates (Baking Soda)", "safety": "green", "note": "Common raising agent; generally safe."},
    "501": {"name": "Potassium Carbonates", "safety": "green", "note": "Generally safe raising agent."},
    "503": {"name": "Ammonium Carbonates", "safety": "green", "note": "Generally safe raising agent in baking."},
    "504": {"name": "Magnesium Carbonates", "safety": "green", "note": "Generally safe; also a magnesium supplement."},
    "508": {"name": "Potassium Chloride", "safety": "green", "note": "Salt substitute; generally safe in food amounts."},
    "509": {"name": "Calcium Chloride", "safety": "green", "note": "Generally safe firming agent."},
    "511": {"name": "Magnesium Chloride", "safety": "green", "note": "Generally safe; used in tofu making."},
    "516": {"name": "Calcium Sulphate", "safety": "green", "note": "Generally safe; used in tofu making."},
    "524": {"name": "Sodium Hydroxide", "safety": "green", "note": "Processing aid; neutralised in final product."},
    "525": {"name": "Potassium Hydroxide", "safety": "green", "note": "Processing aid; neutralised in final product."},
    "526": {"name": "Calcium Hydroxide", "safety": "green", "note": "Processing aid; generally safe."},
    "528": {"name": "Magnesium Hydroxide", "safety": "green", "note": "Generally safe; used as antacid."},
    "535": {"name": "Sodium Ferrocyanide", "safety": "green", "note": "Anti-caking agent in salt; safe at permitted levels."},
    "536": {"name": "Potassium Ferrocyanide", "safety": "green", "note": "Anti-caking agent; safe at permitted levels."},
    "541": {"name": "Sodium Aluminium Phosphate (SALP)", "safety": "yellow", "note": "Aluminium content; high intake concerns."},
    "551": {"name": "Silicon Dioxide (Silica)", "safety": "green", "note": "Anti-caking agent; generally safe."},
    "552": {"name": "Calcium Silicate", "safety": "green", "note": "Anti-caking agent; generally safe."},
    "553": {"name": "Magnesium Silicates (Talc)", "safety": "yellow", "note": "Some concerns with talc purity; moderation advised."},
    "554": {"name": "Sodium Aluminosilicate", "safety": "yellow", "note": "Aluminium content; concerns at high intake."},
    "558": {"name": "Bentonite", "safety": "green", "note": "Natural clay; generally safe as processing aid."},
    "570": {"name": "Fatty Acids", "safety": "green", "note": "Anti-caking agents; generally safe."},
    "574": {"name": "Gluconic Acid", "safety": "green", "note": "Naturally occurring acid; generally safe."},
    "575": {"name": "Glucono Delta-Lactone (GDL)", "safety": "green", "note": "Natural acidifier from glucose; generally safe."},
    "576": {"name": "Sodium Gluconate", "safety": "green", "note": "Generally safe sequestrant."},
    "577": {"name": "Potassium Gluconate", "safety": "green", "note": "Generally safe; also a potassium supplement."},
    "578": {"name": "Calcium Gluconate", "safety": "green", "note": "Generally safe; also a calcium supplement."},

    # ── GLAZING AGENTS / GASES (E900–E949) ────────────────────────────────────
    "900": {"name": "Dimethyl Polysiloxane", "safety": "green", "note": "Anti-foaming agent; generally safe."},
    "901": {"name": "Beeswax", "safety": "green", "note": "Natural wax glazing agent; safe."},
    "902": {"name": "Candelilla Wax", "safety": "green", "note": "Natural plant wax; safe."},
    "903": {"name": "Carnauba Wax", "safety": "green", "note": "Natural wax from Brazilian palm; safe."},
    "904": {"name": "Shellac", "safety": "green", "note": "Natural resin from lac insect; generally safe."},
    "905": {"name": "Microcrystalline Wax", "safety": "green", "note": "Mineral wax; generally safe."},
    "920": {"name": "L-Cysteine", "safety": "green", "note": "Amino acid used in bread making; generally safe."},
    "938": {"name": "Argon", "safety": "green", "note": "Inert packaging gas; safe."},
    "941": {"name": "Nitrogen", "safety": "green", "note": "Inert packaging and propellant gas; safe."},
    "942": {"name": "Nitrous Oxide", "safety": "green", "note": "Propellant for whipped cream; safe in food use."},
    "948": {"name": "Oxygen", "safety": "green", "note": "Packaging gas; safe."},

    # ── MODIFIED STARCHES (E1400–E1452) ──────────────────────────────────────
    "1200": {"name": "Polydextrose", "safety": "green", "note": "Soluble fibre; generally safe, may have mild laxative effect."},
    "1400": {"name": "Dextrin", "safety": "green", "note": "Starch derivative; generally safe."},
    "1404": {"name": "Oxidised Starch", "safety": "green", "note": "Modified starch; generally safe."},
    "1410": {"name": "Monostarch Phosphate", "safety": "green", "note": "Modified starch; generally safe."},
    "1412": {"name": "Distarch Phosphate", "safety": "green", "note": "Modified starch; generally safe."},
    "1413": {"name": "Phosphated Distarch Phosphate", "safety": "green", "note": "Modified starch; generally safe."},
    "1414": {"name": "Acetylated Distarch Phosphate", "safety": "green", "note": "Modified starch; generally safe."},
    "1420": {"name": "Starch Acetate", "safety": "green", "note": "Modified starch; generally safe."},
    "1422": {"name": "Acetylated Distarch Adipate", "safety": "green", "note": "Modified starch; generally safe."},
    "1440": {"name": "Hydroxypropyl Starch", "safety": "green", "note": "Modified starch; generally safe."},
    "1442": {"name": "Hydroxypropyl Distarch Phosphate", "safety": "green", "note": "Modified starch; commonly used thickener; safe."},
    "1450": {"name": "Starch Sodium Octenyl Succinate", "safety": "green", "note": "Modified starch; generally safe."},
    "1505": {"name": "Triethyl Citrate", "safety": "green", "note": "Citric acid ester; generally safe."},
    "1518": {"name": "Glyceryl Triacetate (Triacetin)", "safety": "green", "note": "Generally safe solvent and humectant."},
    "1520": {"name": "Propylene Glycol", "safety": "yellow", "note": "Generally safe in small amounts; high intake not advised."},
}
