# additives_db.py
# Pre-built dictionary of common food additives (E numbers / INS numbers)
# safety: "green" = generally safe, "yellow" = use with caution, "red" = avoid
# Each entry: { "name": str, "safety": str, "note": str }

ADDITIVES_DB = {
    # ── COLOURS ──────────────────────────────────────────────────────────────
    "100": {"name": "Curcumin (Turmeric)", "safety": "green", "note": "Natural colour, generally safe."},
    "101": {"name": "Riboflavin (Vitamin B2)", "safety": "green", "note": "Natural colour and nutrient."},
    "102": {"name": "Tartrazine", "safety": "yellow", "note": "May cause hyperactivity in children; banned in Norway."},
    "104": {"name": "Quinoline Yellow", "safety": "yellow", "note": "Linked to hyperactivity; banned in USA and Australia."},
    "110": {"name": "Sunset Yellow FCF", "safety": "yellow", "note": "May cause hyperactivity; requires warning label in EU."},
    "120": {"name": "Cochineal / Carmine", "safety": "yellow", "note": "Derived from insects; may cause allergic reactions."},
    "122": {"name": "Azorubine / Carmoisine", "safety": "yellow", "note": "Linked to hyperactivity in children."},
    "123": {"name": "Amaranth", "safety": "red", "note": "Banned in USA; ongoing safety concerns."},
    "124": {"name": "Ponceau 4R", "safety": "yellow", "note": "Requires hyperactivity warning in EU."},
    "127": {"name": "Erythrosine", "safety": "yellow", "note": "High iodine content; restricted in some countries."},
    "129": {"name": "Allura Red AC", "safety": "yellow", "note": "Linked to hyperactivity; requires EU warning label."},
    "132": {"name": "Indigotine / Indigo Carmine", "safety": "yellow", "note": "May cause nausea in large amounts."},
    "133": {"name": "Brilliant Blue FCF", "safety": "yellow", "note": "Banned in several European countries."},
    "140": {"name": "Chlorophylls", "safety": "green", "note": "Natural green colour, safe."},
    "141": {"name": "Copper Chlorophylls", "safety": "green", "note": "Natural derivative, generally safe."},
    "150a": {"name": "Caramel Colour (Plain)", "safety": "green", "note": "Generally safe in normal amounts."},
    "150c": {"name": "Caramel Colour (Ammonia)", "safety": "yellow", "note": "May contain trace contaminants; under review."},
    "150d": {"name": "Caramel Colour (Sulfite-ammonia)", "safety": "yellow", "note": "Contains 4-MEI; potential carcinogen under study."},
    "151": {"name": "Brilliant Black BN", "safety": "yellow", "note": "Banned in USA and several other countries."},
    "160a": {"name": "Beta-carotene", "safety": "green", "note": "Natural colour, also a precursor to Vitamin A."},
    "160b": {"name": "Annatto", "safety": "yellow", "note": "May cause allergic reactions in sensitive individuals."},
    "160c": {"name": "Paprika Extract", "safety": "green", "note": "Natural colour from paprika, generally safe."},
    "162": {"name": "Beetroot Red", "safety": "green", "note": "Natural colour, safe."},
    "171": {"name": "Titanium Dioxide", "safety": "red", "note": "Banned as food additive in EU; possible carcinogen."},
    "172": {"name": "Iron Oxides", "safety": "green", "note": "Used in decoration; generally safe at permitted levels."},

    # ── PRESERVATIVES ─────────────────────────────────────────────────────────
    "200": {"name": "Sorbic Acid", "safety": "green", "note": "Generally safe; widely used preservative."},
    "202": {"name": "Potassium Sorbate", "safety": "green", "note": "Generally safe; may cause mild skin irritation."},
    "210": {"name": "Benzoic Acid", "safety": "yellow", "note": "Can form benzene with Vitamin C; avoid combining."},
    "211": {"name": "Sodium Benzoate", "safety": "yellow", "note": "May cause hyperactivity; avoid with ascorbic acid."},
    "212": {"name": "Potassium Benzoate", "safety": "yellow", "note": "Similar concerns as sodium benzoate."},
    "213": {"name": "Calcium Benzoate", "safety": "yellow", "note": "Similar concerns as sodium benzoate."},
    "220": {"name": "Sulphur Dioxide", "safety": "yellow", "note": "Can trigger asthma; must be labelled as allergen."},
    "221": {"name": "Sodium Sulphite", "safety": "yellow", "note": "May cause asthma reactions in sensitive individuals."},
    "223": {"name": "Sodium Metabisulphite", "safety": "yellow", "note": "Sulphite; allergen for asthmatics."},
    "224": {"name": "Potassium Metabisulphite", "safety": "yellow", "note": "Sulphite; allergen for asthmatics."},
    "249": {"name": "Potassium Nitrite", "safety": "red", "note": "Can form carcinogenic nitrosamines; use minimised."},
    "250": {"name": "Sodium Nitrite", "safety": "red", "note": "Linked to cancer risk; used in processed meats."},
    "251": {"name": "Sodium Nitrate", "safety": "yellow", "note": "Converts to nitrite in body; moderation advised."},
    "252": {"name": "Potassium Nitrate", "safety": "yellow", "note": "Converts to nitrite; use in small amounts only."},
    "280": {"name": "Propionic Acid", "safety": "green", "note": "Generally safe; naturally found in Swiss cheese."},
    "281": {"name": "Sodium Propionate", "safety": "green", "note": "Generally safe bread preservative."},
    "282": {"name": "Calcium Propionate", "safety": "green", "note": "Generally safe; widely used in baked goods."},

    # ── ANTIOXIDANTS ──────────────────────────────────────────────────────────
    "300": {"name": "Ascorbic Acid (Vitamin C)", "safety": "green", "note": "Essential vitamin and antioxidant, safe."},
    "301": {"name": "Sodium Ascorbate", "safety": "green", "note": "Vitamin C salt, generally safe."},
    "306": {"name": "Tocopherol (Vitamin E)", "safety": "green", "note": "Natural antioxidant, safe."},
    "307": {"name": "Alpha-tocopherol (Vitamin E)", "safety": "green", "note": "Natural Vitamin E, safe."},
    "310": {"name": "Propyl Gallate", "safety": "yellow", "note": "May cause allergic reactions; under ongoing review."},
    "319": {"name": "TBHQ (Tertiary Butylhydroquinone)", "safety": "yellow", "note": "High doses linked to tumours in animal studies."},
    "320": {"name": "BHA (Butylated Hydroxyanisole)", "safety": "yellow", "note": "Possible carcinogen; banned in Japan."},
    "321": {"name": "BHT (Butylated Hydroxytoluene)", "safety": "yellow", "note": "Ongoing research; some countries restrict use."},

    # ── THICKENERS / STABILISERS / EMULSIFIERS ────────────────────────────────
    "330": {"name": "Citric Acid", "safety": "green", "note": "Naturally found in citrus fruits, generally safe."},
    "331": {"name": "Sodium Citrates", "safety": "green", "note": "Generally safe acidity regulator."},
    "332": {"name": "Potassium Citrates", "safety": "green", "note": "Generally safe acidity regulator."},
    "333": {"name": "Calcium Citrates", "safety": "green", "note": "Generally safe; also a calcium supplement."},
    "334": {"name": "Tartaric Acid", "safety": "green", "note": "Naturally in grapes, generally safe."},
    "338": {"name": "Phosphoric Acid", "safety": "yellow", "note": "High intake linked to reduced bone density."},
    "339": {"name": "Sodium Phosphates", "safety": "yellow", "note": "High intake may affect kidney function."},
    "340": {"name": "Potassium Phosphates", "safety": "yellow", "note": "Moderation advised; high intake affects kidneys."},
    "341": {"name": "Calcium Phosphates", "safety": "green", "note": "Generally safe; used as raising agent."},
    "407": {"name": "Carrageenan", "safety": "yellow", "note": "May cause inflammation in large amounts; under review."},
    "410": {"name": "Locust Bean Gum", "safety": "green", "note": "Natural thickener, generally safe."},
    "412": {"name": "Guar Gum", "safety": "green", "note": "Natural thickener, generally safe."},
    "415": {"name": "Xanthan Gum", "safety": "green", "note": "Generally safe; may cause digestive issues in excess."},
    "420": {"name": "Sorbitol", "safety": "yellow", "note": "Laxative effect in large amounts (>50g/day)."},
    "421": {"name": "Mannitol", "safety": "yellow", "note": "May cause digestive discomfort in large amounts."},
    "422": {"name": "Glycerol", "safety": "green", "note": "Generally safe; naturally occurring."},
    "440": {"name": "Pectin", "safety": "green", "note": "Natural fibre from fruit, safe."},
    "450": {"name": "Diphosphates", "safety": "yellow", "note": "High intake of phosphates linked to kidney issues."},
    "451": {"name": "Triphosphates", "safety": "yellow", "note": "Phosphate load; moderation advised."},
    "452": {"name": "Polyphosphates", "safety": "yellow", "note": "May affect kidney function in high amounts."},
    "460": {"name": "Microcrystalline Cellulose", "safety": "green", "note": "Inert fibre, generally safe."},
    "466": {"name": "Sodium Carboxymethyl Cellulose", "safety": "green", "note": "Generally safe thickener."},
    "471": {"name": "Mono- and Diglycerides of Fatty Acids", "safety": "green", "note": "Widely used emulsifier, generally safe."},
    "472e": {"name": "DATEM", "safety": "yellow", "note": "Generally safe; high intake may affect heart."},
    "476": {"name": "Polyglycerol Polyricinoleate (PGPR)", "safety": "green", "note": "Generally safe; used in chocolate."},
    "481": {"name": "Sodium Stearoyl Lactylate", "safety": "green", "note": "Generally safe emulsifier."},
    "491": {"name": "Sorbitan Monostearate", "safety": "green", "note": "Generally safe emulsifier."},

    # ── FLAVOUR ENHANCERS ─────────────────────────────────────────────────────
    "620": {"name": "Glutamic Acid", "safety": "yellow", "note": "May cause reactions in MSG-sensitive individuals."},
    "621": {"name": "Monosodium Glutamate (MSG)", "safety": "yellow", "note": "May cause reactions in sensitive people."},
    "627": {"name": "Disodium Guanylate", "safety": "yellow", "note": "Often used with MSG; avoid if gout-prone."},
    "631": {"name": "Disodium Inosinate", "safety": "yellow", "note": "Often used with MSG; avoid if gout-prone."},
    "635": {"name": "Disodium Ribonucleotides", "safety": "yellow", "note": "Combination of 627 and 631; same concerns."},

    # ── SWEETENERS ────────────────────────────────────────────────────────────
    "950": {"name": "Acesulfame K", "safety": "yellow", "note": "Some studies suggest effects on gut bacteria."},
    "951": {"name": "Aspartame", "safety": "yellow", "note": "Classified as possibly carcinogenic by IARC (2023)."},
    "952": {"name": "Cyclamate", "safety": "yellow", "note": "Banned in USA; approved in EU with limits."},
    "954": {"name": "Saccharin", "safety": "yellow", "note": "Oldest artificial sweetener; some cancer concerns."},
    "955": {"name": "Sucralose", "safety": "yellow", "note": "May affect gut bacteria; ongoing research."},
    "960": {"name": "Steviol Glycosides (Stevia)", "safety": "green", "note": "Natural sweetener, generally considered safe."},
    "961": {"name": "Neotame", "safety": "green", "note": "Generally safe; approved by major food authorities."},
    "965": {"name": "Maltitol", "safety": "yellow", "note": "Laxative effect in large amounts."},
    "967": {"name": "Xylitol", "safety": "yellow", "note": "Safe for humans; highly toxic to dogs."},

    # ── MISCELLANEOUS ─────────────────────────────────────────────────────────
    "170": {"name": "Calcium Carbonates", "safety": "green", "note": "Generally safe; also a calcium supplement."},
    "500": {"name": "Sodium Carbonates", "safety": "green", "note": "Common raising agent, generally safe."},
    "501": {"name": "Potassium Carbonates", "safety": "green", "note": "Generally safe raising agent."},
    "503": {"name": "Ammonium Carbonates", "safety": "green", "note": "Generally safe raising agent in baking."},
    "508": {"name": "Potassium Chloride", "safety": "green", "note": "Salt substitute; generally safe in food amounts."},
    "509": {"name": "Calcium Chloride", "safety": "green", "note": "Generally safe firming agent."},
    "516": {"name": "Calcium Sulphate", "safety": "green", "note": "Generally safe; used in tofu making."},
    "551": {"name": "Silicon Dioxide", "safety": "green", "note": "Anti-caking agent, generally safe."},
    "553": {"name": "Magnesium Silicates (Talc)", "safety": "yellow", "note": "Some concerns with talc purity; moderation advised."},
    "570": {"name": "Fatty Acids", "safety": "green", "note": "Generally safe anti-caking agents."},
    "575": {"name": "Glucono Delta-Lactone (GDL)", "safety": "green", "note": "Natural acidifier, generally safe."},
    "627": {"name": "Disodium Guanylate", "safety": "yellow", "note": "Avoid if gout-prone; often paired with MSG."},
    "900": {"name": "Dimethyl Polysiloxane", "safety": "green", "note": "Anti-foaming agent, generally safe."},
    "901": {"name": "Beeswax", "safety": "green", "note": "Natural wax coating, safe."},
    "903": {"name": "Carnauba Wax", "safety": "green", "note": "Natural wax from palm leaves, safe."},
    "904": {"name": "Shellac", "safety": "green", "note": "Natural resin coating, generally safe."},
    "407a": {"name": "Processed Eucheuma Seaweed", "safety": "yellow", "note": "Similar concerns as carrageenan."},
}
